Runtime: java
Instance_class: F2
entrypoint: java -Xmx64m -jar hourjob-0.0.1-SNAPSHOT.jar


env: flex


handlers:
  - url: /.*
    script: this field is required, but ignored


env_variables:
  SPRING_PROFILES_ACTIVE: “prod”
#Entrypoint: java-noverify -jar hourjob-0.0.1-SNAPSHOT.jar
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,postgresql"
  URL: "jdbc:postgresql://google/hourjob?cloudSqlInstance=hourjob:us-east1:hourjob&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres&password=root"
  USER: "postgres"
  PASSWORD: "root"


